dist: bionic
services:
  - xvfb
language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
# command to install dependencies
before_install:
  - sudo apt-get install -y python3-dev git gcc libglib2.0-dev libgirepository1.0-dev libcairo2-dev pkg-config gir1.2-gtk-3.0 gir1.2-wnck-3.0
install:
  - pip install -r requirements/linux.txt
  - pip install -r requirements/base_development.txt
  - pytest --cov=arrangeit
# command to run tests
script:
  - pytest
after_success:
  - coveralls