import os

from PIL import Image


BLANK_ICON = Image.open(
    os.path.join(os.path.dirname(__file__), "resources", "blank.png")
)

WINDOW_MODEL_TYPES = {
    "wid": int,
    "rect": (int, int, int, int),
    "resizable": bool,
    "title": str,
    "name": str,
    "icon": Image.Image,
    "workspace": int,
}
WINDOW_RECT_ELEMENTS = ("x", "y", "w", "h")

ROOT_ALPHA = 0.99  # 0.8

WINDOW_SHIFT_PIXELS = 2

SELECTED_COLOR = "blue"
HIGHLIGHTED_COLOR = "red"

TITLE_LABEL_RELHEIGHT = 0.25
TITLE_LABEL_RELWIDTH = 0.75
TITLE_LABEL_ANCHOR = "w"
TITLE_LABEL_BG = "yellow"
TITLE_LABEL_FG = "black"
TITLE_LABEL_FONT_INCREASE = 0.1
TITLE_LABEL_HEIGHT = 3
TITLE_LABEL_PADX = 12
TITLE_LABEL_PADY = 6

ICON_WIDTH = 32
ICON_LABEL_ANCHOR = "n"
ICON_LABEL_BG = "white"
ICON_LABEL_PADX = 2
ICON_LABEL_PADY = 2

NAME_LABEL_RELHEIGHT = 0.25
NAME_LABEL_RELWIDTH = 0.25
NAME_LABEL_ANCHOR = "s"
NAME_LABEL_BG = "white"
NAME_LABEL_FG = "black"
NAME_LABEL_HEIGHT = 3
NAME_LABEL_PADX = 2
NAME_LABEL_PADY = 10

LOCATE, RESIZE, OTHER = 0, 1, 2
WINDOW_MIN_WIDTH = 100
WINDOW_MIN_HEIGHT = 40

WORKSPACES_FRAME_RELHEIGHT = 0.50
WORKSPACES_FRAME_RELWIDTH = 0.25

WORKSPACE_NUMBER_RELHEIGHT = 0.75
WORKSPACE_NUMBER_RELWIDTH = 1.0
WORKSPACE_NUMBER_LABEL_ANCHOR = "center"
WORKSPACE_NUMBER_LABEL_BG = "white"
WORKSPACE_NUMBER_LABEL_FG = "black"
WORKSPACE_NUMBER_FONT_INCREASE = 0.5
WORKSPACE_NUMBER_LABEL_PADX = 2
WORKSPACE_NUMBER_LABEL_PADY = 2

WORKSPACE_NAME_RELHEIGHT = 0.25
WORKSPACE_NAME_RELWIDTH = 1.0
WORKSPACE_NAME_LABEL_ANCHOR = "center"
WORKSPACE_NAME_LABEL_HEIGHT = 2
WORKSPACE_NAME_LABEL_BG = "white"
WORKSPACE_NAME_LABEL_FG = "black"
WORKSPACE_NAME_FONT_INCREASE = -0.4
WORKSPACE_NAME_LABEL_PADX = 0
WORKSPACE_NAME_LABEL_PADY = 0

WINDOWS_LIST_RELHEIGHT = 0.75
WINDOWS_LIST_RELWIDTH = 0.75

LISTED_WINDOW_RELHEIGHT = 0.125
LISTED_WINDOW_RELWIDTH = 0.95
LISTED_WINDOW_LABEL_ANCHOR = "w"
LISTED_WINDOW_LABEL_BG = "white"
LISTED_WINDOW_LABEL_FG = "black"
LISTED_WINDOW_NAME_FONT_INCREASE = -0.1
LISTED_WINDOW_LABEL_PADX = 2
LISTED_WINDOW_LABEL_PADY = 2

LISTED_ICON_LABEL_BG = "white"
LISTED_ICON_LABEL_ANCHOR = "w"
LISTED_ICON_LABEL_PADX = 4
LISTED_ICON_LABEL_PADY = 0
