Vagrant.configure(2) do |config|

  config.vm.define "xfcevm" do |xfcevm|
    xfcevm.vm.box = "generic/ubuntu1904"
    xfcevm.vm.hostname = "xfcevm"
  end

  config.vm.define "gnomevm" do |gnomevm|
    gnomevm.vm.box = "generic/fedora30"
    gnomevm.vm.hostname = "gnomevm"
  end

  config.vm.define "kdevm" do |kdevm|
    kdevm.vm.box = "archlinux/archlinux"
    kdevm.vm.hostname = "kdevm"
  end

  config.vm.define "winvm" do |winvm|
    winvm.vm.box = "inclusivedesign/windows10-eval"  # "StefanScherer/windows_10"
    winvm.vm.hostname = "winvm"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "3072"
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--vram", "32"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "arrangeit-setup.yml"
  end

  config.vm.provision "ansible", run: 'always' do |ansible|
    ansible.verbose = "v"
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "arrangeit-tests.yml"
  end

end
